include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # Freezed uses JSON tags on unconventional places
    # https://pub.dev/documentation/freezed/latest/#disabling-invalid_annotation_target-warning-and-warning-in-generates-files
    invalid_annotation_target: ignore

  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/**/*.mocks.dart
    - test/.test_coverage.dart
    - coverage/**/*
    - lib/**/*.pb.dart
    - lib/**/*.pbjson.dart
    - lib/**/*.pbserver.dart
    - lib/**/*.pbenum.dart

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_positional_boolean_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null: true
    avoid_returning_this: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    close_sinks: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    file_names: true
    hash_and_equals: true
    join_return_with_assignment: true
    library_names: true
    library_prefixes: true
    null_closures: true
    only_throw_errors: true
    package_api_docs: true
    package_names: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    test_types_in_equals: true
    throw_in_finally: true
    type_annotate_public_apis: true
    unnecessary_await_in_return: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unrelated_type_equality_checks: true
    use_key_in_widget_constructors: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true
    void_checks: true

    # Explicity disabled

    # Disable context misuse. context.mounted check seems to be currently 
    # ignored by the linter
    # See https://stackoverflow.com/a/69512692/5165143
    use_build_context_synchronously: false